CREATE ROLE uncleblueberry WITH LOGIN PASSWORD 'superPa55*'
    NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION VALID UNTIL 'infinity';

GRANT CONNECT ON DATABASE cruxdemo TO uncleblueberry;
GRANT USAGE ON SCHEMA public TO uncleblueberry;
GRANT ALL ON ALL TABLES IN SCHEMA public TO uncleblueberry;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO uncleblueberry;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO uncleblueberry;